const { test } = require("node:test");
const assert = require("node:assert");
const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const TOOL = path.join(__dirname, "..", "tools", "approval-status-reason-count.js");
const TIMEOUT = 5_000;
const USAGE = "usage: node app/tools/approval-status-reason-count.js <state-file> <status>\n";
const READ = "approval-status-reason-count: cannot read state file\n";
const PARSE = "approval-status-reason-count: state file is not valid JSON\n";
const INVALID = "approval-status-reason-count: invalid Relay state\n";
const ARITY = "arity-state-MUST-NOT-LEAK.json";
const ABSENT = "PATH-MUST-NOT-LEAK.json";
const DIRECTORY = "DIRECTORY-MUST-NOT-LEAK";

const A_VALUE = { events: [{ payload: "EVENT-PAYLOAD-MUST-NOT-LEAK" }], jobs: [{ lastError: "JOB-ERROR-MUST-NOT-LEAK" }], approvals: [
  { id: "appr-rejected-reason-one", jobId: "job-rejected-reason-one", action: { to: "REASON-ONE-TO-MUST-NOT-LEAK", subject: "REASON-ONE-SUBJECT-MUST-NOT-LEAK", body: "REASON-ONE-BODY-MUST-NOT-LEAK" }, status: "rejected", proposedAt: "2026-08-24T12:00:00.000Z", reason: "REJECTED-REASON-ONE-MUST-NOT-LEAK" },
  { id: "appr-rejected-reason-space", jobId: "job-rejected-reason-space", action: { to: "REASON-SPACE-TO-MUST-NOT-LEAK", subject: "REASON-SPACE-SUBJECT-MUST-NOT-LEAK", body: "REASON-SPACE-BODY-MUST-NOT-LEAK" }, status: "rejected", proposedAt: "2026-08-24T12:00:01.000Z", reason: " " },
  { id: "appr-rejected-reason-empty", jobId: "job-rejected-reason-empty", action: { to: "REASON-EMPTY-TO-MUST-NOT-LEAK", subject: "REASON-EMPTY-SUBJECT-MUST-NOT-LEAK", body: "REASON-EMPTY-BODY-MUST-NOT-LEAK" }, status: "rejected", proposedAt: "2026-08-24T12:00:02.000Z", reason: "" },
  { id: "appr-rejected-reason-null", jobId: "job-rejected-reason-null", action: { to: 7, subject: null, body: false, ignored: "IGNORED-ACTION-FIELD-MUST-NOT-LEAK" }, status: "rejected", proposedAt: "not-an-iso-instant", reason: null, ignoredDiagnostic: "IGNORED-APPROVAL-FIELD-MUST-NOT-LEAK" },
  { id: "appr-rejected-reason-absent", jobId: "job-rejected-reason-absent", action: { to: "REASON-ABSENT-TO-MUST-NOT-LEAK", subject: "REASON-ABSENT-SUBJECT-MUST-NOT-LEAK", body: "REASON-ABSENT-BODY-MUST-NOT-LEAK" }, status: "rejected", proposedAt: "2026-08-24T12:00:04.000Z" },
  { id: "appr-pending-reason", jobId: "job-pending-reason", action: { to: "PENDING-TO-MUST-NOT-LEAK", subject: "PENDING-SUBJECT-MUST-NOT-LEAK", body: "PENDING-BODY-MUST-NOT-LEAK" }, status: "pending", proposedAt: "2026-08-24T12:00:05.000Z", reason: "PENDING-REASON-MUST-NOT-LEAK" },
  { id: "appr-sent-reason", jobId: "job-sent-reason", action: { to: "SENT-TO-MUST-NOT-LEAK", subject: "SENT-SUBJECT-MUST-NOT-LEAK", body: "SENT-BODY-MUST-NOT-LEAK" }, status: "sent", proposedAt: "2026-08-24T12:00:06.000Z", reason: "SENT-REASON-MUST-NOT-LEAK" },
  { id: "appr-blocked-reason", jobId: "job-blocked-reason", action: { to: "BLOCKED-TO-MUST-NOT-LEAK", subject: "BLOCKED-SUBJECT-MUST-NOT-LEAK", body: "BLOCKED-BODY-MUST-NOT-LEAK" }, status: "blocked_recipient", proposedAt: "2026-08-24T12:00:07.000Z", reason: "BLOCKED-REASON-MUST-NOT-LEAK" },
], outbox: [{ body: "OUTBOX-CONTENT-MUST-NOT-LEAK" }], metadata: { note: "TOP-LEVEL-METADATA-MUST-NOT-LEAK" } };
const A = JSON.stringify(A_VALUE, null, 2) + "\n";
const B = '{"events":[null],"jobs":[7],"approvals":[{"id":"appr-absent","jobId":"job-absent","action":{"to":"a","subject":"b","body":"c"},"status":"blocked_recipient","proposedAt":"time-a"},{"id":"appr-null","jobId":"job-null","action":{"to":"d","subject":"e","body":"f"},"status":"blocked_recipient","proposedAt":"time-b","reason":null},{"id":"appr-empty","jobId":"job-empty","action":{"to":"g","subject":"h","body":"i"},"status":"blocked_recipient","proposedAt":"time-c","reason":""},{"id":"appr-other-status","jobId":"job-other","action":{"to":"j","subject":"k","body":"l"},"status":"pending","proposedAt":"time-d","reason":"OTHER-STATUS-REASON-MUST-NOT-LEAK"}],"outbox":["OPAQUE-CONTENT-MUST-NOT-LEAK"],"metadata":false}\n';
const C = '{"approvals":[],"payload":"MALFORMED-PAYLOAD-MUST-NOT-LEAK"\n';
const S = [
  ["S1", "null\n"], ["S2", "[]\n"], ["S3", '{"events":[],"jobs":[],"approvals":[]}\n'], ["S4", '{"events":{},"jobs":[],"approvals":[],"outbox":[]}\n'], ["S5", '{"events":[],"jobs":{},"approvals":[],"outbox":[]}\n'], ["S6", '{"events":[],"jobs":[],"approvals":{},"outbox":[]}\n'], ["S7", '{"events":[],"jobs":[],"approvals":[],"outbox":{}}\n'], ["S8", '{"events":[],"jobs":[],"approvals":[null],"outbox":[]}\n'], ["S9", '{"events":[],"jobs":[],"approvals":[[]],"outbox":[]}\n'],
  ["S10", '{"events":[],"jobs":[],"approvals":[{"jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S11", '{"events":[],"jobs":[],"approvals":[{"id":"","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S12", '{"events":[],"jobs":[],"approvals":[{"id":7,"jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S13", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S14", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S15", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":7,"action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'],
  ["S16", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S17", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":null,"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S18", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":[],"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S19", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S20", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","body":"c"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'], ["S21", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b"},"status":"pending","proposedAt":"time-a"}],"outbox":[]}\n'],
  ["S22", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending"}],"outbox":[]}\n'], ["S23", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":""}],"outbox":[]}\n'], ["S24", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":7}],"outbox":[]}\n'], ["S25", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"proposedAt":"time-a"}],"outbox":[]}\n'], ["S26", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"PENDING","proposedAt":"time-a"}],"outbox":[]}\n'], ["S27", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":null,"proposedAt":"time-a"}],"outbox":[]}\n'], ["S28", '{"events":[],"jobs":[],"approvals":[{"id":"appr-a","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"rejected","proposedAt":"time-a","reason":7}],"outbox":[]}\n'], ["S29", '{"events":[],"jobs":[],"approvals":[{"id":"appr-duplicate","jobId":"job-a","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a"},{"id":"appr-duplicate","jobId":"job-b","action":{"to":"d","subject":"e","body":"f"},"status":"sent","proposedAt":"time-b"}],"outbox":[]}\n'], ["S30", '{"events":[],"jobs":[],"approvals":[{"id":"appr-valid-first","jobId":"job-valid","action":{"to":"a","subject":"b","body":"c"},"status":"pending","proposedAt":"time-a","reason":"count-me"},{"id":"appr-invalid-second","jobId":"job-invalid","action":{"to":"d","subject":"e","body":"f"},"status":"rejected","proposedAt":"time-b","reason":false}],"outbox":[]}\n'],
];
const TOKENS = [...new Set([...(A + B + C + ARITY + ABSENT + DIRECTORY).match(/[A-Za-z0-9-]*MUST-NOT-LEAK(?:\.json)?/g) || [], ARITY.slice(0, -5), ABSENT.slice(0, -5)])];
function own(o, k) { return Object.prototype.hasOwnProperty.call(o, k); }
function temp(label) { return fs.mkdtempSync(path.join(os.tmpdir(), `relay-approval-status-reason-count-${label}-`)); }
function write(dir, content) { const file = path.join(dir, "state.json"); fs.writeFileSync(file, content); return file; }
function fileSnap(file) { const s = fs.statSync(file, { bigint: true }); return { bytes: fs.readFileSync(file).toString("hex"), mode: s.mode, size: s.size, mtimeNs: s.mtimeNs }; }
function dirSnap(dir) { const s = fs.statSync(dir, { bigint: true }); return { entries: fs.readdirSync(dir).sort(), mode: s.mode, size: s.size, mtimeNs: s.mtimeNs }; }
function run(args) { const r = spawnSync(process.execPath, [TOOL, ...args], { stdio: "pipe", timeout: TIMEOUT }); assert.strictEqual(r.error, undefined); assert.strictEqual(r.signal, null); const stdout = r.stdout.toString(); const stderr = r.stderr.toString(); for (const t of TOKENS) { assert.strictEqual(stdout.includes(t), false, `stdout leaked ${t}`); assert.strictEqual(stderr.includes(t), false, `stderr leaked ${t}`); } return { status: r.status, stdout, stderr, out: r.stdout.length, err: r.stderr.length }; }
function assertResult(r, status, stdout, stderr) { assert.strictEqual(r.status, status); assert.strictEqual(r.stdout, stdout); assert.strictEqual(r.stderr, stderr); if (stdout === "") assert.strictEqual(r.out, 0); if (stderr === "") assert.strictEqual(r.err, 0); }
function specifiers(source) { return [...new Set([...source.matchAll(/require\(\s*["']([^"']+)["']\s*\)/g)].map(m => m[1]))].sort(); }

test("AC1: Fixture A counts exactly the two rejected approvals with own non-empty string reasons", () => { const a = A_VALUE.approvals; assert.strictEqual(a.length, 8); assert.deepStrictEqual(a.slice(0, 5).map(x => x.reason), ["REJECTED-REASON-ONE-MUST-NOT-LEAK", " ", "", null, undefined]); assert.strictEqual(own(a[4], "reason"), false); assert.deepStrictEqual(a.map(x => x.status), ["rejected", "rejected", "rejected", "rejected", "rejected", "pending", "sent", "blocked_recipient"]); const d = temp("ac1"); try { const f = write(d, A); const before = fileSnap(f); const entries = fs.readdirSync(d).sort(); assertResult(run([f, "rejected"]), 0, '{"approvalsWithStatusAndReason":2}\n', ""); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); assertResult(run([f, "REJECTED"]), 0, '{"approvalsWithStatusAndReason":0}\n', ""); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); } finally { fs.rmSync(d, { recursive: true, force: true }); } });
test("AC2: Fixture B counts zero blocked-recipient approvals with absent, null, or empty reasons", () => { const b = JSON.parse(B); assert.deepStrictEqual(b.approvals.map(x => [x.status, own(x, "reason") ? x.reason : undefined]), [["blocked_recipient", undefined], ["blocked_recipient", null], ["blocked_recipient", ""], ["pending", "OTHER-STATUS-REASON-MUST-NOT-LEAK"]]); assert.deepStrictEqual([b.events, b.jobs, b.outbox, b.metadata], [[null], [7], ["OPAQUE-CONTENT-MUST-NOT-LEAK"], false]); const d = temp("ac2"); try { const f = write(d, B); const before = fileSnap(f); const entries = fs.readdirSync(d).sort(); assertResult(run([f, "blocked_recipient"]), 0, '{"approvalsWithStatusAndReason":0}\n', ""); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); } finally { fs.rmSync(d, { recursive: true, force: true }); } });
test("AC3: zero, one, and three arguments return the exact usage error without creating paths", () => { for (const [label, args] of [["zero", []], ["one", null], ["three", null]]) { const d = temp(`ac3-${label}`); try { const p = path.join(d, ARITY); const actual = label === "zero" ? args : label === "one" ? [p] : [p, "rejected", "extra"]; assertResult(run(actual), 2, "", USAGE); assert.strictEqual(fs.existsSync(p), false); assert.deepStrictEqual(fs.readdirSync(d).sort(), []); } finally { fs.rmSync(d, { recursive: true, force: true }); } } });
test("AC4: absent files and directories return the exact redacted read error without mutation", () => { const d = temp("ac4-absent"); try { const p = path.join(d, ABSENT); const before = fs.readdirSync(d).sort(); assertResult(run([p, "rejected"]), 1, "", READ); assert.strictEqual(fs.existsSync(p), false); assert.deepStrictEqual(fs.readdirSync(d).sort(), before); } finally { fs.rmSync(d, { recursive: true, force: true }); } const q = temp("ac4-directory"); try { const p = path.join(q, DIRECTORY); fs.mkdirSync(p); const before = dirSnap(p); const parent = fs.readdirSync(q).sort(); assertResult(run([p, "rejected"]), 1, "", READ); assert.strictEqual(fs.statSync(p).isDirectory(), true); assert.deepStrictEqual(dirSnap(p), before); assert.deepStrictEqual(fs.readdirSync(q).sort(), parent); } finally { fs.rmSync(q, { recursive: true, force: true }); } });
test("AC5: malformed and zero-byte JSON files return the exact parse error without leaking bytes", () => { for (const [label, bytes] of [["C", C], ["D", ""]]) { const d = temp(`ac5-${label}`); try { const f = write(d, bytes); const before = fileSnap(f); const entries = fs.readdirSync(d).sort(); assertResult(run([f, "rejected"]), 1, "", PARSE); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); } finally { fs.rmSync(d, { recursive: true, force: true }); } } });
test("AC6: every S1-S30 structural-invalid fixture is rejected before status filtering", () => { const all = [["A", A], ["B", B], ["C", C], ["D", ""], ...S]; for (let i = 0; i < all.length; i += 1) for (let j = i + 1; j < all.length; j += 1) assert.notStrictEqual(all[i][1], all[j][1]); const s26 = JSON.parse(S[25][1]); assert.strictEqual(s26.approvals[0].status, "PENDING"); assert.notStrictEqual(s26.approvals[0].status, "pending"); const s30 = JSON.parse(S[29][1]); assert.strictEqual(s30.approvals[0].reason, "count-me"); assert.strictEqual(s30.approvals[1].reason, false); for (const [label, bytes] of S) { const d = temp(`ac6-${label}`); try { const f = write(d, bytes); const before = fileSnap(f); const entries = fs.readdirSync(d).sort(); assertResult(run([f, "rejected"]), 1, "", INVALID); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); } finally { fs.rmSync(d, { recursive: true, force: true }); } } });
test("AC7: child invocations time out safely and source boundaries are exact", () => { const d = temp("ac7"); try { const f = write(d, A); assertResult(run([f, "rejected"]), 0, '{"approvalsWithStatusAndReason":2}\n', ""); } finally { fs.rmSync(d, { recursive: true, force: true }); } assert.strictEqual(fs.existsSync(TOOL), true); const source = fs.readFileSync(TOOL, "utf8"); assert.deepStrictEqual(specifiers(source), ["node:fs"]); const operations = [...source.matchAll(/\bfs\s*\.\s*([A-Za-z_$][\w$]*)/g)].map(m => m[1]); assert.deepStrictEqual([...new Set(operations)].sort(), ["readFileSync"]); for (const forbidden of ["server.js", "fetch(", "WebSocket", "node:http", "node:https", "node:net", "node:child_process", "setTimeout", "setInterval"]) assert.strictEqual(source.includes(forbidden), false); assert.deepStrictEqual(specifiers(fs.readFileSync(__filename, "utf8")), ["node:assert", "node:child_process", "node:fs", "node:os", "node:path", "node:test"]); });
test("AC8: the test-author commit precedes the builder commit and each creates only its owned path", () => { const testPath = "app/tests/approval-status-reason-count.test.js"; const builderPath = "app/tools/approval-status-reason-count.js"; assert.strictEqual(fs.existsSync(builderPath), true, "builder file exists after implementation"); const log = args => { const r = spawnSync("git", args, { encoding: "utf8" }); assert.strictEqual(r.status, 0); return r.stdout.trim().split("\n").filter(Boolean); }; const testCommits = log(["log", "--format=%H", "--reverse", "--", testPath]); const builderCommits = log(["log", "--format=%H", "--reverse", "--", builderPath]); assert.strictEqual(testCommits.length, 1, "one test-author commit owns the test path"); assert.strictEqual(builderCommits.length, 1, "one builder commit owns the builder path"); const all = log(["log", "--format=%H", "--reverse"]); assert.ok(all.indexOf(testCommits[0]) < all.indexOf(builderCommits[0]), "test commit precedes builder commit"); for (const [commit, owned] of [[testCommits[0], testPath], [builderCommits[0], builderPath]]) { const files = log(["show", "--format=", "--name-only", commit]); assert.deepStrictEqual(files, [owned], `${commit} creates only ${owned}`); } });
test("AC9: an empty-string status query is accepted as the second positional argument and yields zero", () => { const d = temp("ac9"); try { const f = write(d, A); const before = fileSnap(f); const entries = fs.readdirSync(d).sort(); assertResult(run([f, ""]), 0, '{"approvalsWithStatusAndReason":0}\n', ""); assert.deepStrictEqual(fileSnap(f), before); assert.deepStrictEqual(fs.readdirSync(d).sort(), entries); } finally { fs.rmSync(d, { recursive: true, force: true }); } });
